apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold-telepresence-demo
build:
  local:
    useBuildkit: true
    useDockerCLI: true
  artifacts:
  - image: innoq/skaffold-telepresence-demo
    context: .
    docker:
      dockerfile: docker/prod.Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize/base

profiles:
- name: dev
  build:
    artifacts:
    - image: innoq/skaffold-telepresence-demo
      docker:
        dockerfile: docker/dev.Dockerfile
- name: sandbox
  build:
    artifacts:
    - image: innoq/skaffold-telepresence-demo
      docker:
        dockerfile: docker/prod.Dockerfile

