apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold-telepresence-demo
build:
  local:
    useBuildkit: true
    useDockerCLI: true
  artifacts:
  - image: demo-app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize/base
